// Compiles the page scripts in client/*.ts (TypeScript, type-checked with the rest of the repo) to the
// JavaScript the browser runs, with Node's own type stripper (the same one that runs these scripts;
// erasableSyntaxOnly in tsconfig keeps every file strippable), and writes them as strings to
// lib/client.generated.ts (gitignored). The server inlines each one where its page needs it, so a
// script still runs before the first paint, with no extra request. Runs before dev, build and check.
//   node scripts/build-client.ts [--watch]
import { readdirSync, readFileSync, writeFileSync, watch } from "node:fs"
import { stripTypeScriptTypes } from "node:module"

const DIR = "client", OUT = "lib/client.generated.ts"

function build() {
  const scripts: Record<string, string> = {}
  for (const file of readdirSync(DIR).filter((f) => f.endsWith(".ts")).sort()) {
    const stripped = stripTypeScriptTypes(readFileSync(`${DIR}/${file}`, "utf8"), { mode: "strip" })
    // Each file is a module (export {}) so names never clash; in the page it runs as its own scope.
    // Whole-line comments are dropped: they are for the source, not the page.
    const body = stripped.split("\n").filter((l) => !/^\s*\/\//.test(l) && !/^export \{\};?\s*$/.test(l) && l.trim())
      .map((l) => l.trim().replace(/[ \t]{2,}/g, " ")).join("\n")
    const js = `(()=>{\n${body}\n})()`
    if (/<\/script/i.test(js)) throw new Error(`client/${file} contains "</script", which would end the inline script`)
    scripts[file.replace(/\.ts$/, "")] = js
  }
  writeFileSync(OUT, `// Generated by scripts/build-client.ts from client/*.ts. Do not edit.\nexport const CLIENT = ${JSON.stringify(scripts, null, 2)} as const\n`)
  console.log(`client: ${Object.keys(scripts).length} page scripts → ${OUT}`)
}

build()
if (process.argv.includes("--watch")) watch(DIR, { persistent: true }, () => { try { build() } catch (e) { console.error(String(e)) } })
