// Compiles the page scripts in client/*.ts (TypeScript, type-checked with the rest of the repo) to the
// JavaScript the browser runs, with Node's own type stripper (the same one that runs these scripts;
// erasableSyntaxOnly in tsconfig keeps every file strippable), and writes them as strings to
// lib/client.generated.ts (gitignored). The server inlines each one where its page needs it, so a
// script still runs before the first paint, with no extra request. Runs before dev, build and check.
// Two kinds of file, told apart by the file itself:
//   no import  a classic script, wrapped in a function so its names never leak; <script>
//   an import  an ES module (it can import three.js and the like through the page's importmap),
//              emitted as it is; <script type="module">  (CLIENT_MODULES lists these)
// client/*.d.ts files are types only and are not compiled.
//   node scripts/build-client.ts [--watch]
import { readdirSync, readFileSync, writeFileSync, watch } from "node:fs"
import { stripTypeScriptTypes } from "node:module"

const DIR = "client", OUT = "lib/client.generated.ts"

function build() {
  const scripts: Record<string, string> = {}
  const modules: string[] = []
  for (const file of readdirSync(DIR).filter((f) => f.endsWith(".ts") && !f.endsWith(".d.ts")).sort()) {
    const stripped = stripTypeScriptTypes(readFileSync(`${DIR}/${file}`, "utf8"), { mode: "strip" })
    // Each file is a module (export {}) so names never clash; in the page it runs as its own scope.
    // Whole-line comments are dropped: they are for the source, not the page.
    const body = stripped.split("\n").filter((l) => !/^\s*\/\//.test(l) && !/^export \{\};?\s*$/.test(l) && l.trim())
      .map((l) => l.trim().replace(/[ \t]{2,}/g, " ")).join("\n")
    const name = file.replace(/\.ts$/, "")
    const isModule = /^import\s+(?!\()/m.test(stripped) // a top-level import (type imports are already gone)
    const js = isModule ? body : `(()=>{\n${body}\n})()`
    if (/<\/script/i.test(js)) throw new Error(`client/${file} contains "</script", which would end the inline script`)
    scripts[name] = js
    if (isModule) modules.push(name)
  }
  writeFileSync(OUT, `// Generated by scripts/build-client.ts from client/*.ts. Do not edit.\nexport const CLIENT = ${JSON.stringify(scripts, null, 2)} as const\n` +
    `/** The scripts that are ES modules: inline each as <script type="module">; every other one as <script>. */\n` +
    `export const CLIENT_MODULES: readonly string[] = ${JSON.stringify(modules)}\n`)
  console.log(`client: ${Object.keys(scripts).length} page scripts (${modules.length} modules) → ${OUT}`)
}

build()
if (process.argv.includes("--watch")) watch(DIR, { persistent: true }, () => { try { build() } catch (e) { console.error(String(e)) } })
